# Generated by Django 6.0.5 on 2026-05-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='phone_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
