# Generated by Django 6.0.5 on 2026-05-25 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_phone_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='default_max_installments',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_installments_allowed', models.PositiveSmallIntegerField(default=5)),
                ('first_due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Aguardando escolha do cliente'), ('accepted', 'Parcelamento escolhido'), ('canceled', 'Cancelada')], default='pending', max_length=20)),
                ('selected_installments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('selected_monthly_interest_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('selected_installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selected_total_with_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sales', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
