# Generated by Django 6.0.5 on 2026-05-25 00:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientprofile_default_max_installments_creditsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='sale_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='max_installments_allowed',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='CreditSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='sale_products/')),
                ('shoe_size', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.creditsale')),
            ],
        ),
    ]
