# Generated by Django 6.0.5 on 2026-05-25 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_creditsale_sale_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='credit_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='accounts.creditsale'),
        ),
    ]
