# Generated by Django 6.0.5 on 2026-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_alter_creditsaleproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profile_photos/'),
        ),
    ]
