# Generated by Django 6.0.5 on 2026-05-29 04:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_clientprofile_pre_approved_credit_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('revenda_calcados', 'Revenda de Calcados')], default='revenda_calcados', max_length=50)),
                ('supplier_code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('product_url', models.URLField(blank=True)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('dropshipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('suggested_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('sizes', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'supplier_code'],
                'constraints': [models.UniqueConstraint(fields=('source', 'supplier_code'), name='unique_supplier_product_code')],
            },
        ),
    ]
