# Generated by Django 6.0.5 on 2026-05-29 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_supplierproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=180)),
                ('supplier_code', models.CharField(max_length=120)),
                ('selected_size', models.CharField(max_length=30)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('shipping_address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Aguardando pagamento'), ('paid', 'Pago - comprar no fornecedor'), ('payment_failed', 'Pagamento recusado'), ('supplier_ordered', 'Pedido feito no fornecedor'), ('shipped', 'Enviado ao cliente'), ('canceled', 'Cancelado')], default='pending_payment', max_length=30)),
                ('mercado_pago_preference_id', models.CharField(blank=True, max_length=120)),
                ('mercado_pago_payment_id', models.CharField(blank=True, max_length=120)),
                ('mercado_pago_init_point', models.URLField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_ordered_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_order_reference', models.CharField(blank=True, max_length=120)),
                ('tracking_code', models.CharField(blank=True, max_length=120)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_orders', to='accounts.supplierproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
