# Generated by Django 6.0.5 on 2026-05-31 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_creditsale_mercado_pago_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditsale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Aguardando pagamento'), ('paid', 'Pago'), ('failed', 'Pagamento recusado')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=120, unique=True)),
                ('status_detail', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_alerts', to='accounts.creditsale')),
                ('store_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_alerts', to='accounts.storeorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
