# Generated by Django 6.0.5 on 2026-06-01 16:11

from django.db import migrations, models
from django.utils import timezone


def three_months_from(date_value):
    month = date_value.month + 3
    year = date_value.year + (month - 1) // 12
    month = (month - 1) % 12 + 1
    month_days = [31, 29 if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0) else 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

    return date_value.replace(year=year, month=month, day=min(date_value.day, month_days[month - 1]))


def activate_existing_vouchers(apps, schema_editor):
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    ClientProfile.objects.filter(
        registration_status="approved",
        first_purchase_discount_used=False,
        welcome_discount_expires_at__isnull=True,
    ).update(welcome_discount_expires_at=three_months_from(timezone.localdate()))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='welcome_discount_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='checkout_reference',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(activate_existing_vouchers, migrations.RunPython.noop),
    ]
