# Generated by Django 5.2.14 on 2026-06-05 03:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_clientprofile_rg_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='shipping_state',
            field=models.CharField(blank=True, choices=[('DF', 'DF'), ('ENTORNO_DF', 'Entorno do DF'), ('GO', 'GO'), ('TO', 'TO'), ('MG', 'MG'), ('SP', 'SP'), ('MS', 'MS'), ('MT', 'MT'), ('PR', 'PR'), ('BA', 'BA'), ('PI', 'PI'), ('MA', 'MA'), ('PA', 'PA'), ('RO', 'RO'), ('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('CE', 'CE'), ('ES', 'ES'), ('PB', 'PB'), ('PE', 'PE'), ('RJ', 'RJ'), ('RN', 'RN'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE')], max_length=20),
        ),
    ]
