# Generated by Django 6.0.5 on 2026-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_user_deletion_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='phone_verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
