# Generated by Django 5.2.14 on 2026-06-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_make_active_stock_products_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='image_file',
            field=models.FileField(blank=True, upload_to='supplier_products/'),
        ),
    ]
