# Generated by Django 6.0.5 on 2026-06-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_add_image_file_to_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='debt',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debt',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
