# Generated by Django 6.0.5 on 2026-06-21 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_seed_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsaleproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='accounts.supplier'),
        ),
        migrations.AddField(
            model_name='creditsaleproduct',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
