# Generated by Django 6.0.5 on 2026-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_salesitem_supplier_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
