# Generated by Django 6.0.5 on 2026-06-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_creditsale_public_token_guest_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='identity_document_back',
            field=models.FileField(blank=True, upload_to='identity_documents/'),
        ),
    ]
