# Generated by Django 6.0.5 on 2026-07-03 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_cashbacktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='referral_bonus_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashbacktransaction',
            name='kind',
            field=models.CharField(choices=[('earn', 'Ganho'), ('redeem', 'Resgate'), ('adjust', 'Ajuste'), ('referral', 'Indicação')], default='earn', max_length=10),
        ),
    ]
