# Generated by Django 6.0.5 on 2026-07-04 00:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_clientprofile_referral_bonus_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='cashback_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
