# Generated by Django 6.0.5 on 2026-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_storeorder_cashback_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldebt',
            name='scope',
            field=models.CharField(choices=[('personal', 'Pessoal'), ('business', 'Empresarial')], default='personal', max_length=20),
        ),
    ]
