# Generated by Django 6.0.5 on 2026-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_personaldebt_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
