# Generated by Django 6.0.5 on 2026-07-05 10:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_clientprofile_marketing_opt_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('cashback_max_redeem_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('referral_bonus', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
