# Generated by Django 6.0.5 on 2026-09-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_storesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliercatalogsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("revenda_calcados", "Revenda de Calcados"),
                    ("parceiro_sob_consulta", "Parceiro sob consulta"),
                    ("novo_fornecedor", "Fornecedor novo"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="source",
            field=models.CharField(
                choices=[
                    ("revenda_calcados", "Revenda de Calcados"),
                    ("parceiro_sob_consulta", "Parceiro sob consulta"),
                    ("novo_fornecedor", "Fornecedor novo"),
                ],
                default="revenda_calcados",
                max_length=50,
            ),
        ),
    ]
