# Generated by Django 6.0.5 on 2026-09-01 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_set_referral_bonus_to_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='points_cap',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='teto de pontos'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='points_card',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='pontos por compra no cartao'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='points_credit',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='pontos por compra no crediario'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='points_payoff_bonus',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='bonus de quitacao do carne'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='points_pix',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='pontos por compra a vista/Pix'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='referral_points',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='pontos por indicacao'),
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earn', 'Ganho em compra'), ('redeem', 'Resgate'), ('referral', 'Indicacao'), ('payoff', 'Bonus de quitacao'), ('adjust', 'Ajuste'), ('expire', 'Expiracao')], default='earn', max_length=10)),
                ('points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='accounts.creditsale')),
                ('store_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='accounts.storeorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
