# Generated by Django 6.0.5 on 2026-09-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_pontos_fidelidade_fundacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('pix', 'A vista / Pix'), ('card', 'Cartao')], max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='points_active',
            field=models.BooleanField(default=False, verbose_name='usar pontos no lugar do cashback'),
        ),
    ]
