# Generated by Django 6.0.5 on 2026-09-03 03:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_pontos_ligados_nas_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='points_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='points_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='pix_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='desconto do pagamento a vista/Pix (%)'),
        ),
    ]
