# Generated by Django 6.0.5 on 2026-09-05 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_resgate_de_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='altura (cm)'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='highlights',
            field=models.TextField(blank=True, verbose_name='principais recursos'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='destaque na pagina inicial'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='comprimento (cm)'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='tech_specs',
            field=models.TextField(blank=True, verbose_name='ficha tecnica'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='video_file',
            field=models.FileField(blank=True, upload_to='product_videos/', verbose_name='arquivo de video'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='link do video'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='peso bruto (g)'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='largura (cm)'),
        ),
        migrations.CreateModel(
            name='SupplierProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='supplier_products/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accounts.supplierproduct')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='cor')),
                ('code', models.CharField(blank=True, max_length=60, verbose_name='codigo')),
                ('image', models.FileField(blank=True, upload_to='supplier_products/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='accounts.supplierproduct')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
