# Generated by Django 6.0.5 on 2026-09-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_catalogo_smartwatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercatalogsource',
            name='source',
            field=models.CharField(choices=[('revenda_calcados', 'Revenda de Calcados'), ('parceiro_sob_consulta', 'Parceiro sob consulta'), ('wearzone', 'Smartwatches e audio')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='source',
            field=models.CharField(choices=[('revenda_calcados', 'Revenda de Calcados'), ('parceiro_sob_consulta', 'Parceiro sob consulta'), ('wearzone', 'Smartwatches e audio')], default='revenda_calcados', max_length=50),
        ),
    ]
