# Generated by Django 6.0.5 on 2026-09-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_origem_wearzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='titulo')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('video', models.FileField(upload_to='reels/', verbose_name='video')),
                ('poster', models.FileField(blank=True, upload_to='reels/', verbose_name='capa do video')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_visible', models.BooleanField(default=True, verbose_name='mostrar na loja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='accounts.supplierproduct', verbose_name='produto ligado')),
            ],
            options={
                'verbose_name': 'reel da loja',
                'verbose_name_plural': 'reels da loja',
                'ordering': ['position', '-created_at'],
            },
        ),
    ]
