# Generated by Django 6.0.5 on 2026-09-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_reels_da_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='card_installments',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='parcelas sem juros no cartao'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='credit_surcharge_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='acrescimo do crediario deste produto (%)'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='pix_discount_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='desconto a vista/Pix deste produto (%)'),
        ),
    ]
