# Generated by Django 6.0.5 on 2026-09-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_regras_por_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereel',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='link do YouTube'),
        ),
        migrations.AlterField(
            model_name='storereel',
            name='video',
            field=models.FileField(blank=True, upload_to='reels/', verbose_name='arquivo de video'),
        ),
    ]
