# Generated by Django 6.0.5 on 2026-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_reels_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoDeEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivos_bytes', models.BigIntegerField(default=0)),
                ('arquivos_quantidade', models.PositiveIntegerField(default=0)),
                ('banco_bytes', models.BigIntegerField(default=0)),
                ('medido_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'uso de espaco',
                'verbose_name_plural': 'uso de espaco',
            },
        ),
    ]
