# Generated by Django 6.0.5 on 2026-09-05 20:58

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_usodeespaco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereel',
            name='poster',
            field=models.FileField(blank=True, storage=accounts.storage.midia_da_vitrine, upload_to='reels/', verbose_name='capa do video'),
        ),
        migrations.AlterField(
            model_name='storereel',
            name='video',
            field=models.FileField(blank=True, storage=accounts.storage.midia_da_vitrine, upload_to='reels/', verbose_name='arquivo de video'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='image_file',
            field=models.FileField(blank=True, storage=accounts.storage.midia_da_vitrine, upload_to='supplier_products/'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='video_file',
            field=models.FileField(blank=True, storage=accounts.storage.midia_da_vitrine, upload_to='product_videos/', verbose_name='arquivo de video'),
        ),
        migrations.AlterField(
            model_name='supplierproductphoto',
            name='image',
            field=models.FileField(storage=accounts.storage.midia_da_vitrine, upload_to='supplier_products/'),
        ),
        migrations.AlterField(
            model_name='supplierproductvariant',
            name='image',
            field=models.FileField(blank=True, storage=accounts.storage.midia_da_vitrine, upload_to='supplier_products/'),
        ),
    ]
