# Generated by Django 6.0.5 on 2026-09-07 09:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_alter_storereel_poster_alter_storereel_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='credit_contract_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='entry_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='entry_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='entry_waived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='entry_waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entry_waivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='principal_financed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_credit_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debt',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='CreditAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('issued', 'Aguardando assinatura'), ('submitted', 'Em conferência'), ('verified', 'Conferido'), ('rejected', 'Novo envio necessário')], default='issued', max_length=16)),
                ('signed_document', models.FileField(blank=True, upload_to='credit_contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_agreements', to='accounts.clientprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_credit_agreements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditAgreementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, max_length=150)),
                ('seller_cpf', models.CharField(blank=True, max_length=14)),
                ('seller_phone', models.CharField(blank=True, max_length=30)),
                ('terms', models.TextField(default='1. Aprovação e utilização\nO crediário destina-se exclusivamente a compras com o vendedor identificado neste documento, sem saque ou transferência em dinheiro. A concessão depende da aprovação cadastral e da conferência do contrato assinado pelo gov.br.\n\n2. Entrada\nClientes novos pagam R$ 20,00 de entrada apenas na primeira compra no crediário. As compras seguintes não exigem entrada. A entrada integra o preço, não é uma taxa adicional e reduz o valor financiado. O resumo específico de cada compra define o valor final da entrada e o valor a parcelar.\n\n3. Limite disponível\nO comprador poderá consultar o limite total, o valor utilizado e o saldo disponível em seu painel. Cada compra utiliza o limite pelo valor principal financiado, sem incluir a entrada, juros ou encargos. O valor correspondente ao principal de cada parcela volta ao saldo após a confirmação do pagamento. Juros e multas não geram crédito adicional. A recomposição não aumenta o limite aprovado. Estornos e cancelamentos ajustam o saldo.\n\n4. Condições de cada compra\nAntes do aceite, cada compra terá resumo com produtos, preço, entrada, valor financiado, parcelas, vencimentos, juros e total a pagar. O comprador deve conferir essas condições antes de confirmar. Este termo, por si só, não representa uma compra nem cria dívida. Condições específicas previamente aceitas integram este contrato.\n\n5. Pagamentos\nAs parcelas deverão ser pagas nos vencimentos acordados. Em caso de atraso, aplicam-se os encargos informados no resumo da compra, observados os limites legais. Novas compras poderão ficar suspensas enquanto houver pagamentos pendentes. As cobranças serão privadas e respeitosas.\n\n6. Antecipação e direitos\nO comprador poderá antecipar pagamentos com redução proporcional dos juros e demais acréscimos. Cancelamentos e devoluções serão tratados conforme os direitos do consumidor, sem duplicidade de crédito. Mudanças no limite para novas compras serão comunicadas e não alterarão as condições já contratadas.\n\n7. Dados pessoais\nOs dados necessários serão utilizados para análise cadastral, execução deste contrato, registro de pagamentos e cumprimento de obrigações legais. O comprador declara que os dados fornecidos são verdadeiros e manterá seus contatos atualizados. Solicitações poderão ser encaminhadas ao telefone do vendedor.\n\n8. Assinatura eletrônica\nAs partes concordam com a assinatura eletrônica pelo gov.br, com conta prata ou ouro. Após a aprovação, o documento preenchido será disponibilizado para assinatura. Cada parte terá acesso à cópia eletrônica assinada. Permanecem preservados os direitos legalmente assegurados ao comprador.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_contract_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
