# Generated by Django 6.0.5 on 2026-09-07 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_preservar_crediario_existente'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='credit_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='accounts.creditagreement'),
        ),
    ]
