# Generated by Django 6.0.5 on 2026-09-07 22:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_vincular_contrato_a_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercatalogsource',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.40'), help_text='1,40 quer dizer custo x 1,40. Vale para as proximas importacoes deste fornecedor.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('9.99'))], verbose_name='margem sobre o custo'),
        ),
    ]
