# Generated by Django 6.0.5 on 2026-09-09 01:29

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_margem_revenda_em_1_60'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='hero_image',
            field=models.FileField(blank=True, help_text='Foto larga (16:9). O texto entra do lado esquerdo, entao deixe esse lado calmo.', storage=accounts.storage.midia_da_vitrine, upload_to='site/', verbose_name='foto da primeira tela'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_image_mobile',
            field=models.FileField(blank=True, help_text='Mesma cena em pe (4:5). Opcional: sem ela, o celular usa a foto larga.', storage=accounts.storage.midia_da_vitrine, upload_to='site/', verbose_name='foto da primeira tela no celular'),
        ),
    ]
