# Generated by Django 6.0.5 on 2026-09-09 02:44

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_storesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaDoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='título')),
                ('chamada', models.CharField(blank=True, max_length=160, verbose_name='linha de apoio')),
                ('imagem', models.FileField(help_text='16:9, com o lado esquerdo calmo: e onde entra o texto.', storage=accounts.storage.midia_da_vitrine, upload_to='capa/', verbose_name='foto larga')),
                ('imagem_celular', models.FileField(blank=True, help_text='4:5. Sem ela, o celular corta a foto larga.', storage=accounts.storage.midia_da_vitrine, upload_to='capa/', verbose_name='foto em pé')),
                ('categoria', models.CharField(blank=True, help_text='Ao clicar, o cliente cai na loja filtrada por esta categoria.', max_length=120, verbose_name='categoria')),
                ('posicao', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('visivel', models.BooleanField(default=True, verbose_name='mostrar no site')),
            ],
            options={
                'verbose_name': 'capa do site',
                'verbose_name_plural': 'capas do site',
                'ordering': ['posicao', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='hero_image_mobile',
        ),
    ]
