# Generated by Django 6.0.5 on 2026-09-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_capas_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='posicao_na_home',
            field=models.PositiveSmallIntegerField(default=0, help_text='1 e o primeiro lugar. Deixe 0 para o site escolher pelo preco.', verbose_name='ordem na primeira tela'),
        ),
    ]
