# Generated by Django 6.0.5 on 2026-09-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_horizon_na_frente_da_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='posicao_na_home',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='1 e o primeiro lugar. Deixe em branco para o site escolher pelo preco.', verbose_name='ordem na primeira tela'),
        ),
    ]
