# Generated by Django 6.0.5 on 2026-09-10 10:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_desconto_do_pix_em_dez'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='points_signup',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='pontos por se cadastrar'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='points_signup_google',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='pontos por se cadastrar com o Google'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='kind',
            field=models.CharField(choices=[('earn', 'Ganho em compra'), ('redeem', 'Resgate'), ('referral', 'Indicacao'), ('payoff', 'Bonus de quitacao'), ('signup', 'Cadastro'), ('adjust', 'Ajuste'), ('expire', 'Expiracao')], default='earn', max_length=10),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='pix_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='desconto do pagamento a vista/Pix (%)'),
        ),
    ]
