# Generated by Django 6.0.5 on 2026-09-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_pontos_por_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='selected_color',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
