# Generated by Django 6.0.5 on 2026-09-11 11:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_tenis_primeira_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='pix_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='points_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='points_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
